
# Global configuration of TLS:
# [global.tls]
# certs = "c:/code/lang/rust/proj/rocket-auth-login/examples/tls_example/private/certs.pem"
# key = "c:/code/lang/rust/proj/rocket-auth-login/examples/tls_example/private/key.pem"
# [global.tls]
# certs = "private\\certs.pem"
# key = "private\\key.pem"


# Or:

# Per Environment Configuration of TLS:
[development]
tls = { certs = "c:\\code\\lang\\rust\\proj\\rocket-auth-login\\examples\\tls_example\\private\\certs.pem", key = "c:\\code\\lang\\rust\\proj\\rocket-auth-login\\examples\\tls_example\\private\\key.pem" }
[production]
tls = { certs = "c:\\code\\lang\\rust\\proj\\rocket-auth-login\\examples\\tls_example\\private\\certs.pem", key = "c:\\code\\lang\\rust\\proj\\rocket-auth-login\\examples\\tls_example\\private\\key.pem" }




